### ISSUE TITLE
[BUG] HA 2024.11.0 Breaks the Camera Integration

### ISSUE THREAD

**Issue by iceman73** [romedtino/simple-wyze-vac#87]
**Describe the bug**
Wyze Camera is not created in the integration upon upgrade to HA Core 2024.11.00

**To Reproduce**
1. Upgrade to HA Coe 2024.11.0
2. See camera disabled and not provided by integration
3.  See error in the log

> Error while setting up simple_wyze_vac platform for camera
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
>     await asyncio.shield(awaitable)
>   File "/config/custom_components/simple_wyze_vac/camera.py", line 15, in async_setup_entry
>     cameras.append(SWVCamera(pl,f"www/{DOMAIN}/{pl['name']}_last_map.jpg"))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/simple_wyze_vac/camera.py", line 21, in __init__
>     super().__init__(pl["name"], file_path)
> TypeError: LocalFile.__init__() missing 1 required positional argument: 'unique_id'

**Expected behavior**
To Work like Ayze worked in 2024.10.4.

**Simple Wyze Vac Version**
- 1.9.1

**Home Assistant Version**
- 2024.11.0

**Additional context**
Downgrade to 2024.10.4 Fixes issue

**Comment by romedtino** [comment]
Fixed in upcoming release. Pre-release https://github.com/romedtino/simple-wyze-vac/releases/tag/1.9.2 available too if you are interested

**Comment by iceman73** [comment]
TY this fixed the issue
